import torch as th
import numpy as np

#Load the dataset here

dataset = th.load("natural_images.pt")

# You can use the Code from sample_query_for_image_labels.py to query the model and get the logits for the images in the dataset

# Example of conversion from pt containing adversarial examples to npz file containing perturbations

def pt_to_npz(base_data, adv_examples, npz_path):
    """
    This function converts adversarial examples stored in adv_examples into the submitted file format (.npz)

    Arguments:

    base_data is the file containing the ground truth images
    adv_examples is the file containing the adversarial examples generated by the participants
    npz_path is the path where the .npz file will be saved

    The generated .npz file can be used to evaluate your results using sample_submission_task2.py
    """
    base_images = base_data["images"]
    adv_images = adv_examples["images"]

    if not isinstance(base_images, th.Tensor) or not isinstance(adv_images, th.Tensor):
        raise TypeError("base_data['images'] and adv_examples['images'] must be torch.Tensor")

    adv_length = len(adv_images)
    cut_base = base_images[:adv_length]
    perturbations = (adv_images - cut_base).cpu().numpy().astype(np.float16)

    if perturbations.dtype == np.object_:
        raise ValueError("Perturbations array has dtype=object, which is unsafe to save.")
    
    np.savez_compressed(npz_path, perturbations=perturbations, allow_pickle=False)

# Generate a pt file with random images and labels
random_labels = th.randint(0, 9, (len(dataset['images']), 1))
random_images = dataset['images'] + th.randn_like(dataset['images']) * 0.1
random_pt = {'images': random_images}

# Convert this to an npz file of perturbations
pt_to_npz(dataset, random_pt, npz_path="perturbations.npz")

# Use the generated .npz file to evaluate your results using sample_submission_task2.py
